
set_property CONFIG_VOLTAGE 3.3 [current_design]
set_property BITSTREAM.CONFIG.SPI_32BIT_ADDR YES [current_design]
set_property CFGBVS VCCO [current_design]


#This is the 125MHz from the White Rabbit PLL/multiplier:
#set_property IOSTANDARD LVDS [get_ports sys_diff_clock_clk_p]
#set_property DIFF_TERM TRUE [get_ports sys_diff_clock_clk_n]
#set_property DIFF_TERM TRUE [get_ports sys_diff_clock_clk_p]
#set_property PACKAGE_PIN AC18 [get_ports sys_diff_clock_clk_p]
#H6
set_property PACKAGE_PIN H6 [get_ports mgt_clk_0_clk_p]
#To direct the 1GbE connection to the on-board SFP:
set_property PACKAGE_PIN R4 [get_ports sfp_0_rxp]
#To direct it to the mobo
#set_property PACKAGE_PIN R4 [get_ports sfp_0_rxp]

#This is the 10MHz reference from SMA1
#set_property IOSTANDARD LVDS [get_ports SMA1_p]
#set_property DIFF_TERM TRUE [get_ports SMA1_p]
#set_property DIFF_TERM TRUE [get_ports SMA1_n]
#set_property PACKAGE_PIN AB17 [get_ports SMA1_p]

set_property PACKAGE_PIN N3 [get_ports sfp_1_rxn]
set_property PACKAGE_PIN N4 [get_ports sfp_1_rxp]
set_property PACKAGE_PIN M1 [get_ports sfp_1_txn]
set_property PACKAGE_PIN M2 [get_ports sfp_1_txp]

set_property IOSTANDARD LVDS [get_ports sysclkin_p]
set_property DIFF_TERM TRUE [get_ports sysclkin_p]
set_property DIFF_TERM TRUE [get_ports sysclkin_n]
#set_property PACKAGE_PIN AC16 [get_ports sysclkin_n]
set_property PACKAGE_PIN AB16 [get_ports sysclkin_p]

set_property IOSTANDARD LVDS [get_ports sysclkout_p]
set_property DIFF_TERM TRUE [get_ports sysclkout_p]
#set_property PACKAGE_PIN AE20 [get_ports sysclkout_n]
set_property PACKAGE_PIN AD20 [get_ports sysclkout_p]


#set_property IOSTANDARD LVCMOS33 [get_ports {SPI_SS[5]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {SPI_SS[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SPI_SS[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SPI_SS[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SPI_SS[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SPI_SS[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports MISO]
set_property IOSTANDARD LVCMOS33 [get_ports MOSI]
set_property IOSTANDARD LVCMOS33 [get_ports SPI_CK]
#set_property PACKAGE_PIN K16 [get_ports {SPI_SS[5]}]
#set_property PACKAGE_PIN D26 [get_ports {SPI_SS[4]}]
set_property PACKAGE_PIN A24 [get_ports {SPI_SS[3]}]
set_property PACKAGE_PIN A23 [get_ports {SPI_SS[2]}]
set_property PACKAGE_PIN B26 [get_ports {SPI_SS[1]}]
set_property PACKAGE_PIN J19 [get_ports {SPI_SS[0]}]
set_property PACKAGE_PIN J18 [get_ports MISO]
set_property PACKAGE_PIN J20 [get_ports MOSI]
set_property PACKAGE_PIN K20 [get_ports SPI_CK]
set_property IOSTANDARD LVCMOS18 [get_ports {maroc_trig0_0[*]}]
set_property IOSTANDARD LVCMOS18 [get_ports {maroc_trig1_0[*]}]
set_property IOSTANDARD LVCMOS18 [get_ports {maroc_trig2_0[*]}]
set_property IOSTANDARD LVCMOS18 [get_ports {maroc_trig3_0[*]}]
set_property PACKAGE_PIN AE26 [get_ports {maroc_trig0_0[0]}]
set_property PACKAGE_PIN AE23 [get_ports {maroc_trig0_0[1]}]
set_property PACKAGE_PIN K26 [get_ports {maroc_trig0_0[10]}]
set_property PACKAGE_PIN R26 [get_ports {maroc_trig0_0[11]}]
set_property PACKAGE_PIN P26 [get_ports {maroc_trig0_0[12]}]
set_property PACKAGE_PIN M25 [get_ports {maroc_trig0_0[13]}]
set_property PACKAGE_PIN L25 [get_ports {maroc_trig0_0[14]}]
set_property PACKAGE_PIN P24 [get_ports {maroc_trig0_0[15]}]
set_property PACKAGE_PIN N24 [get_ports {maroc_trig0_0[16]}]
set_property PACKAGE_PIN N26 [get_ports {maroc_trig0_0[17]}]
set_property PACKAGE_PIN M26 [get_ports {maroc_trig0_0[18]}]
set_property PACKAGE_PIN R25 [get_ports {maroc_trig0_0[19]}]
set_property PACKAGE_PIN AF23 [get_ports {maroc_trig0_0[2]}]
set_property PACKAGE_PIN P25 [get_ports {maroc_trig0_0[20]}]
set_property PACKAGE_PIN N19 [get_ports {maroc_trig0_0[21]}]
set_property PACKAGE_PIN M20 [get_ports {maroc_trig0_0[22]}]
set_property PACKAGE_PIN M24 [get_ports {maroc_trig0_0[23]}]
set_property PACKAGE_PIN L24 [get_ports {maroc_trig0_0[24]}]
set_property PACKAGE_PIN P19 [get_ports {maroc_trig0_0[25]}]
set_property PACKAGE_PIN P20 [get_ports {maroc_trig0_0[26]}]
set_property PACKAGE_PIN M21 [get_ports {maroc_trig0_0[27]}]
set_property PACKAGE_PIN M22 [get_ports {maroc_trig0_0[28]}]
set_property PACKAGE_PIN P23 [get_ports {maroc_trig0_0[29]}]
set_property PACKAGE_PIN AD25 [get_ports {maroc_trig0_0[3]}]
set_property PACKAGE_PIN N23 [get_ports {maroc_trig0_0[30]}]
set_property PACKAGE_PIN N21 [get_ports {maroc_trig0_0[31]}]
set_property PACKAGE_PIN N22 [get_ports {maroc_trig0_0[32]}]
set_property PACKAGE_PIN R21 [get_ports {maroc_trig0_0[33]}]
set_property PACKAGE_PIN P21 [get_ports {maroc_trig0_0[34]}]
set_property PACKAGE_PIN R22 [get_ports {maroc_trig0_0[35]}]
set_property PACKAGE_PIN R23 [get_ports {maroc_trig0_0[36]}]
set_property PACKAGE_PIN T24 [get_ports {maroc_trig0_0[37]}]
set_property PACKAGE_PIN T25 [get_ports {maroc_trig0_0[38]}]
set_property PACKAGE_PIN T20 [get_ports {maroc_trig0_0[39]}]
set_property PACKAGE_PIN AE25 [get_ports {maroc_trig0_0[4]}]
set_property PACKAGE_PIN R20 [get_ports {maroc_trig0_0[40]}]
set_property PACKAGE_PIN T22 [get_ports {maroc_trig0_0[41]}]
set_property PACKAGE_PIN T23 [get_ports {maroc_trig0_0[42]}]
set_property PACKAGE_PIN U19 [get_ports {maroc_trig0_0[43]}]
set_property PACKAGE_PIN U20 [get_ports {maroc_trig0_0[44]}]
set_property PACKAGE_PIN T18 [get_ports {maroc_trig0_0[45]}]
set_property PACKAGE_PIN T19 [get_ports {maroc_trig0_0[46]}]
set_property PACKAGE_PIN P16 [get_ports {maroc_trig0_0[47]}]
set_property PACKAGE_PIN N17 [get_ports {maroc_trig0_0[48]}]
set_property PACKAGE_PIN R16 [get_ports {maroc_trig0_0[49]}]
set_property PACKAGE_PIN AE22 [get_ports {maroc_trig0_0[5]}]
set_property PACKAGE_PIN R17 [get_ports {maroc_trig0_0[50]}]
set_property PACKAGE_PIN N18 [get_ports {maroc_trig0_0[51]}]
set_property PACKAGE_PIN M19 [get_ports {maroc_trig0_0[52]}]
set_property PACKAGE_PIN U17 [get_ports {maroc_trig0_0[53]}]
set_property PACKAGE_PIN T17 [get_ports {maroc_trig0_0[54]}]
set_property PACKAGE_PIN R18 [get_ports {maroc_trig0_0[55]}]
set_property PACKAGE_PIN P18 [get_ports {maroc_trig0_0[56]}]
set_property PACKAGE_PIN U16 [get_ports {maroc_trig0_0[57]}]
set_property PACKAGE_PIN AF14 [get_ports {maroc_trig0_0[58]}]
set_property PACKAGE_PIN AF15 [get_ports {maroc_trig0_0[59]}]
set_property PACKAGE_PIN AF22 [get_ports {maroc_trig0_0[6]}]
set_property PACKAGE_PIN AE18 [get_ports {maroc_trig0_0[60]}]
set_property PACKAGE_PIN AF18 [get_ports {maroc_trig0_0[61]}]
set_property PACKAGE_PIN AD15 [get_ports {maroc_trig0_0[62]}]
set_property PACKAGE_PIN AE15 [get_ports {maroc_trig0_0[63]}]
set_property PACKAGE_PIN Y20 [get_ports {maroc_trig0_0[7]}]
set_property PACKAGE_PIN N16 [get_ports {maroc_trig0_0[8]}]
set_property PACKAGE_PIN K25 [get_ports {maroc_trig0_0[9]}]
set_property PACKAGE_PIN B12 [get_ports {maroc_trig1_0[0]}]
set_property PACKAGE_PIN B11 [get_ports {maroc_trig1_0[1]}]
set_property PACKAGE_PIN C14 [get_ports {maroc_trig1_0[10]}]
set_property PACKAGE_PIN C12 [get_ports {maroc_trig1_0[11]}]
set_property PACKAGE_PIN C11 [get_ports {maroc_trig1_0[12]}]
set_property PACKAGE_PIN C13 [get_ports {maroc_trig1_0[13]}]
set_property PACKAGE_PIN D11 [get_ports {maroc_trig1_0[14]}]
set_property PACKAGE_PIN F14 [get_ports {maroc_trig1_0[15]}]
set_property PACKAGE_PIN F13 [get_ports {maroc_trig1_0[16]}]
set_property PACKAGE_PIN G12 [get_ports {maroc_trig1_0[17]}]
set_property PACKAGE_PIN F12 [get_ports {maroc_trig1_0[18]}]
set_property PACKAGE_PIN D14 [get_ports {maroc_trig1_0[19]}]
set_property PACKAGE_PIN B14 [get_ports {maroc_trig1_0[2]}]
set_property PACKAGE_PIN D13 [get_ports {maroc_trig1_0[20]}]
set_property PACKAGE_PIN E13 [get_ports {maroc_trig1_0[21]}]
set_property PACKAGE_PIN U21 [get_ports {maroc_trig1_0[22]}]
set_property PACKAGE_PIN U22 [get_ports {maroc_trig1_0[23]}]
set_property PACKAGE_PIN V22 [get_ports {maroc_trig1_0[24]}]
set_property PACKAGE_PIN U24 [get_ports {maroc_trig1_0[25]}]
set_property PACKAGE_PIN U25 [get_ports {maroc_trig1_0[26]}]
set_property PACKAGE_PIN V23 [get_ports {maroc_trig1_0[27]}]
set_property PACKAGE_PIN V24 [get_ports {maroc_trig1_0[28]}]
set_property PACKAGE_PIN U26 [get_ports {maroc_trig1_0[29]}]
set_property PACKAGE_PIN A14 [get_ports {maroc_trig1_0[3]}]
set_property PACKAGE_PIN V26 [get_ports {maroc_trig1_0[30]}]
set_property PACKAGE_PIN W25 [get_ports {maroc_trig1_0[31]}]
set_property PACKAGE_PIN W26 [get_ports {maroc_trig1_0[32]}]
set_property PACKAGE_PIN V21 [get_ports {maroc_trig1_0[33]}]
set_property PACKAGE_PIN W21 [get_ports {maroc_trig1_0[34]}]
set_property PACKAGE_PIN AA25 [get_ports {maroc_trig1_0[35]}]
set_property PACKAGE_PIN AB25 [get_ports {maroc_trig1_0[36]}]
set_property PACKAGE_PIN W23 [get_ports {maroc_trig1_0[37]}]
set_property PACKAGE_PIN W24 [get_ports {maroc_trig1_0[38]}]
set_property PACKAGE_PIN AB26 [get_ports {maroc_trig1_0[39]}]
set_property PACKAGE_PIN B10 [get_ports {maroc_trig1_0[4]}]
set_property PACKAGE_PIN AC26 [get_ports {maroc_trig1_0[40]}]
set_property PACKAGE_PIN Y25 [get_ports {maroc_trig1_0[41]}]
set_property PACKAGE_PIN Y26 [get_ports {maroc_trig1_0[42]}]
set_property PACKAGE_PIN AA23 [get_ports {maroc_trig1_0[43]}]
set_property PACKAGE_PIN AB24 [get_ports {maroc_trig1_0[44]}]
set_property PACKAGE_PIN Y23 [get_ports {maroc_trig1_0[45]}]
set_property PACKAGE_PIN AA24 [get_ports {maroc_trig1_0[46]}]
set_property PACKAGE_PIN Y22 [get_ports {maroc_trig1_0[47]}]
set_property PACKAGE_PIN AA22 [get_ports {maroc_trig1_0[48]}]
set_property PACKAGE_PIN AC23 [get_ports {maroc_trig1_0[49]}]
set_property PACKAGE_PIN A10 [get_ports {maroc_trig1_0[5]}]
set_property PACKAGE_PIN AC24 [get_ports {maroc_trig1_0[50]}]
set_property PACKAGE_PIN W20 [get_ports {maroc_trig1_0[51]}]
set_property PACKAGE_PIN Y21 [get_ports {maroc_trig1_0[52]}]
set_property PACKAGE_PIN AD23 [get_ports {maroc_trig1_0[53]}]
set_property PACKAGE_PIN AD24 [get_ports {maroc_trig1_0[54]}]
set_property PACKAGE_PIN AB22 [get_ports {maroc_trig1_0[55]}]
set_property PACKAGE_PIN AC22 [get_ports {maroc_trig1_0[56]}]
set_property PACKAGE_PIN AB21 [get_ports {maroc_trig1_0[57]}]
set_property PACKAGE_PIN AC21 [get_ports {maroc_trig1_0[58]}]
set_property PACKAGE_PIN AD21 [get_ports {maroc_trig1_0[59]}]
set_property PACKAGE_PIN B15 [get_ports {maroc_trig1_0[6]}]
set_property PACKAGE_PIN AE21 [get_ports {maroc_trig1_0[60]}]
set_property PACKAGE_PIN AF24 [get_ports {maroc_trig1_0[61]}]
set_property PACKAGE_PIN AF25 [get_ports {maroc_trig1_0[62]}]
set_property PACKAGE_PIN AD26 [get_ports {maroc_trig1_0[63]}]
set_property PACKAGE_PIN A15 [get_ports {maroc_trig1_0[7]}]
set_property PACKAGE_PIN F10 [get_ports {maroc_trig1_0[8]}]
set_property PACKAGE_PIN E12 [get_ports {maroc_trig1_0[9]}]
set_property PACKAGE_PIN AB10 [get_ports {maroc_trig2_0[0]}]
set_property PACKAGE_PIN AB12 [get_ports {maroc_trig2_0[1]}]
set_property PACKAGE_PIN AE11 [get_ports {maroc_trig2_0[10]}]
set_property PACKAGE_PIN AD10 [get_ports {maroc_trig2_0[11]}]
set_property PACKAGE_PIN AE10 [get_ports {maroc_trig2_0[12]}]
set_property PACKAGE_PIN AE12 [get_ports {maroc_trig2_0[13]}]
set_property PACKAGE_PIN AF12 [get_ports {maroc_trig2_0[14]}]
set_property PACKAGE_PIN AE8 [get_ports {maroc_trig2_0[15]}]
set_property PACKAGE_PIN AF8 [get_ports {maroc_trig2_0[16]}]
set_property PACKAGE_PIN AE13 [get_ports {maroc_trig2_0[17]}]
set_property PACKAGE_PIN AF13 [get_ports {maroc_trig2_0[18]}]
set_property PACKAGE_PIN AF10 [get_ports {maroc_trig2_0[19]}]
set_property PACKAGE_PIN AC12 [get_ports {maroc_trig2_0[2]}]
set_property PACKAGE_PIN AF9 [get_ports {maroc_trig2_0[20]}]
set_property PACKAGE_PIN V12 [get_ports {maroc_trig2_0[21]}]
set_property PACKAGE_PIN E10 [get_ports {maroc_trig2_0[22]}]
set_property PACKAGE_PIN D10 [get_ports {maroc_trig2_0[23]}]
set_property PACKAGE_PIN E11 [get_ports {maroc_trig2_0[24]}]
set_property PACKAGE_PIN F8 [get_ports {maroc_trig2_0[25]}]
set_property PACKAGE_PIN D9 [get_ports {maroc_trig2_0[26]}]
set_property PACKAGE_PIN D8 [get_ports {maroc_trig2_0[27]}]
set_property PACKAGE_PIN A9 [get_ports {maroc_trig2_0[28]}]
set_property PACKAGE_PIN A8 [get_ports {maroc_trig2_0[29]}]
set_property PACKAGE_PIN AA13 [get_ports {maroc_trig2_0[3]}]
set_property PACKAGE_PIN C9 [get_ports {maroc_trig2_0[30]}]
set_property PACKAGE_PIN B9 [get_ports {maroc_trig2_0[31]}]
set_property PACKAGE_PIN G11 [get_ports {maroc_trig2_0[32]}]
set_property PACKAGE_PIN A13 [get_ports {maroc_trig2_0[33]}]
set_property PACKAGE_PIN A12 [get_ports {maroc_trig2_0[34]}]
set_property PACKAGE_PIN J14 [get_ports {maroc_trig2_0[35]}]
set_property PACKAGE_PIN U9 [get_ports {maroc_trig2_0[36]}]
set_property PACKAGE_PIN V11 [get_ports {maroc_trig2_0[37]}]
set_property PACKAGE_PIN W11 [get_ports {maroc_trig2_0[38]}]
set_property PACKAGE_PIN V8 [get_ports {maroc_trig2_0[39]}]
set_property PACKAGE_PIN AA12 [get_ports {maroc_trig2_0[4]}]
set_property PACKAGE_PIN V7 [get_ports {maroc_trig2_0[40]}]
set_property PACKAGE_PIN W10 [get_ports {maroc_trig2_0[41]}]
set_property PACKAGE_PIN W9 [get_ports {maroc_trig2_0[42]}]
set_property PACKAGE_PIN Y8 [get_ports {maroc_trig2_0[43]}]
set_property PACKAGE_PIN Y7 [get_ports {maroc_trig2_0[44]}]
set_property PACKAGE_PIN Y11 [get_ports {maroc_trig2_0[45]}]
set_property PACKAGE_PIN Y10 [get_ports {maroc_trig2_0[46]}]
set_property PACKAGE_PIN V9 [get_ports {maroc_trig2_0[47]}]
set_property PACKAGE_PIN W8 [get_ports {maroc_trig2_0[48]}]
set_property PACKAGE_PIN AE7 [get_ports {maroc_trig2_0[49]}]
set_property PACKAGE_PIN AC13 [get_ports {maroc_trig2_0[5]}]
set_property PACKAGE_PIN AF7 [get_ports {maroc_trig2_0[50]}]
set_property PACKAGE_PIN AA8 [get_ports {maroc_trig2_0[51]}]
set_property PACKAGE_PIN AA7 [get_ports {maroc_trig2_0[52]}]
set_property PACKAGE_PIN AC8 [get_ports {maroc_trig2_0[53]}]
set_property PACKAGE_PIN AD8 [get_ports {maroc_trig2_0[54]}]
set_property PACKAGE_PIN AB7 [get_ports {maroc_trig2_0[55]}]
set_property PACKAGE_PIN AC7 [get_ports {maroc_trig2_0[56]}]
set_property PACKAGE_PIN AA9 [get_ports {maroc_trig2_0[57]}]
set_property PACKAGE_PIN AB9 [get_ports {maroc_trig2_0[58]}]
set_property PACKAGE_PIN AC9 [get_ports {maroc_trig2_0[59]}]
set_property PACKAGE_PIN AD13 [get_ports {maroc_trig2_0[6]}]
set_property PACKAGE_PIN AD9 [get_ports {maroc_trig2_0[60]}]
set_property PACKAGE_PIN AB11 [get_ports {maroc_trig2_0[61]}]
set_property PACKAGE_PIN AC11 [get_ports {maroc_trig2_0[62]}]
set_property PACKAGE_PIN AA10 [get_ports {maroc_trig2_0[63]}]
set_property PACKAGE_PIN Y13 [get_ports {maroc_trig2_0[7]}]
set_property PACKAGE_PIN Y12 [get_ports {maroc_trig2_0[8]}]
set_property PACKAGE_PIN AD11 [get_ports {maroc_trig2_0[9]}]
set_property PACKAGE_PIN U4 [get_ports {maroc_trig3_0[0]}]
set_property PACKAGE_PIN U6 [get_ports {maroc_trig3_0[1]}]
set_property PACKAGE_PIN V6 [get_ports {maroc_trig3_0[10]}]
set_property PACKAGE_PIN V4 [get_ports {maroc_trig3_0[11]}]
set_property PACKAGE_PIN W4 [get_ports {maroc_trig3_0[12]}]
set_property PACKAGE_PIN Y3 [get_ports {maroc_trig3_0[13]}]
set_property PACKAGE_PIN Y2 [get_ports {maroc_trig3_0[14]}]
set_property PACKAGE_PIN V2 [get_ports {maroc_trig3_0[15]}]
set_property PACKAGE_PIN V1 [get_ports {maroc_trig3_0[16]}]
set_property PACKAGE_PIN AB1 [get_ports {maroc_trig3_0[17]}]
set_property PACKAGE_PIN AC1 [get_ports {maroc_trig3_0[18]}]
set_property PACKAGE_PIN W1 [get_ports {maroc_trig3_0[19]}]
set_property PACKAGE_PIN U5 [get_ports {maroc_trig3_0[2]}]
set_property PACKAGE_PIN Y1 [get_ports {maroc_trig3_0[20]}]
set_property PACKAGE_PIN AB2 [get_ports {maroc_trig3_0[21]}]
set_property PACKAGE_PIN AC2 [get_ports {maroc_trig3_0[22]}]
set_property PACKAGE_PIN AA3 [get_ports {maroc_trig3_0[23]}]
set_property PACKAGE_PIN AA2 [get_ports {maroc_trig3_0[24]}]
set_property PACKAGE_PIN AA4 [get_ports {maroc_trig3_0[25]}]
set_property PACKAGE_PIN AB4 [get_ports {maroc_trig3_0[26]}]
set_property PACKAGE_PIN AC4 [get_ports {maroc_trig3_0[27]}]
set_property PACKAGE_PIN AC3 [get_ports {maroc_trig3_0[28]}]
set_property PACKAGE_PIN AA5 [get_ports {maroc_trig3_0[29]}]
set_property PACKAGE_PIN U2 [get_ports {maroc_trig3_0[3]}]
set_property PACKAGE_PIN AB5 [get_ports {maroc_trig3_0[30]}]
set_property PACKAGE_PIN AB6 [get_ports {maroc_trig3_0[31]}]
set_property PACKAGE_PIN AC6 [get_ports {maroc_trig3_0[32]}]
set_property PACKAGE_PIN Y6 [get_ports {maroc_trig3_0[33]}]
set_property PACKAGE_PIN Y5 [get_ports {maroc_trig3_0[34]}]
set_property PACKAGE_PIN AD6 [get_ports {maroc_trig3_0[35]}]
set_property PACKAGE_PIN AD5 [get_ports {maroc_trig3_0[36]}]
set_property PACKAGE_PIN AD4 [get_ports {maroc_trig3_0[37]}]
set_property PACKAGE_PIN AD3 [get_ports {maroc_trig3_0[38]}]
set_property PACKAGE_PIN AD1 [get_ports {maroc_trig3_0[39]}]
set_property PACKAGE_PIN U1 [get_ports {maroc_trig3_0[4]}]
set_property PACKAGE_PIN AE1 [get_ports {maroc_trig3_0[40]}]
set_property PACKAGE_PIN AF5 [get_ports {maroc_trig3_0[41]}]
set_property PACKAGE_PIN AF4 [get_ports {maroc_trig3_0[42]}]
set_property PACKAGE_PIN AE3 [get_ports {maroc_trig3_0[43]}]
set_property PACKAGE_PIN AE2 [get_ports {maroc_trig3_0[44]}]
set_property PACKAGE_PIN AE6 [get_ports {maroc_trig3_0[45]}]
set_property PACKAGE_PIN AE5 [get_ports {maroc_trig3_0[46]}]
set_property PACKAGE_PIN AF3 [get_ports {maroc_trig3_0[47]}]
set_property PACKAGE_PIN AF2 [get_ports {maroc_trig3_0[48]}]
set_property PACKAGE_PIN T7 [get_ports {maroc_trig3_0[49]}]
set_property PACKAGE_PIN W6 [get_ports {maroc_trig3_0[5]}]
set_property PACKAGE_PIN J8 [get_ports {maroc_trig3_0[50]}]
set_property PACKAGE_PIN H9 [get_ports {maroc_trig3_0[51]}]
set_property PACKAGE_PIN H8 [get_ports {maroc_trig3_0[52]}]
set_property PACKAGE_PIN G10 [get_ports {maroc_trig3_0[53]}]
set_property PACKAGE_PIN G9 [get_ports {maroc_trig3_0[54]}]
set_property PACKAGE_PIN J13 [get_ports {maroc_trig3_0[55]}]
set_property PACKAGE_PIN H13 [get_ports {maroc_trig3_0[56]}]
set_property PACKAGE_PIN J11 [get_ports {maroc_trig3_0[57]}]
set_property PACKAGE_PIN J10 [get_ports {maroc_trig3_0[58]}]
set_property PACKAGE_PIN H14 [get_ports {maroc_trig3_0[59]}]
set_property PACKAGE_PIN W5 [get_ports {maroc_trig3_0[6]}]
set_property PACKAGE_PIN G14 [get_ports {maroc_trig3_0[60]}]
set_property PACKAGE_PIN H12 [get_ports {maroc_trig3_0[61]}]
set_property PACKAGE_PIN H11 [get_ports {maroc_trig3_0[62]}]
set_property PACKAGE_PIN F9 [get_ports {maroc_trig3_0[63]}]
set_property PACKAGE_PIN V3 [get_ports {maroc_trig3_0[7]}]
set_property PACKAGE_PIN W3 [get_ports {maroc_trig3_0[8]}]
set_property PACKAGE_PIN U7 [get_ports {maroc_trig3_0[9]}]
set_property IOSTANDARD LVCMOS18 [get_ports {or_trig0_0[*]}]
set_property IOSTANDARD LVCMOS18 [get_ports {or_trig1_0[*]}]
set_property IOSTANDARD LVCMOS18 [get_ports {or_trig2_0[*]}]
set_property IOSTANDARD LVCMOS18 [get_ports {or_trig3_0[*]}]
set_property PACKAGE_PIN AF20 [get_ports {or_trig0_0[1]}]
set_property PACKAGE_PIN AF19 [get_ports {or_trig0_0[0]}]
set_property PACKAGE_PIN AE16 [get_ports {or_trig1_0[1]}]
set_property PACKAGE_PIN AD16 [get_ports {or_trig1_0[0]}]
set_property PACKAGE_PIN AA15 [get_ports {or_trig2_0[1]}]
set_property PACKAGE_PIN AA14 [get_ports {or_trig2_0[0]}]
set_property PACKAGE_PIN AD14 [get_ports {or_trig3_0[1]}]
set_property PACKAGE_PIN AC14 [get_ports {or_trig3_0[0]}]
set_property IOSTANDARD LVDS [get_ports {ADC_DIN_P[*]}]
set_property IOSTANDARD LVDS [get_ports {BIT_CLK_P[*]}]
set_property IOSTANDARD LVDS [get_ports FRM_CLK_P]
set_property PACKAGE_PIN Y17 [get_ports {ADC_DIN_P[3]}]
set_property PACKAGE_PIN AB19 [get_ports {ADC_DIN_P[2]}]
set_property PACKAGE_PIN AC19 [get_ports {ADC_DIN_P[1]}]
set_property PACKAGE_PIN AA19 [get_ports {ADC_DIN_P[0]}]
set_property PACKAGE_PIN V16 [get_ports {BIT_CLK_P[0]}]
set_property PACKAGE_PIN W18 [get_ports FRM_CLK_P]
set_property IOSTANDARD LVCMOS33 [get_ports {RSTB_R[*]}]
set_property IOSTANDARD LVCMOS33 [get_ports {D_R[*]}]
set_property IOSTANDARD LVCMOS33 [get_ports {CK_R[*]}]
set_property IOSTANDARD LVCMOS33 [get_ports {hold1[*]}]
set_property IOSTANDARD LVCMOS33 [get_ports {hold2[*]}]

set_property PACKAGE_PIN B17 [get_ports {RSTB_R[0]}]
set_property PACKAGE_PIN G16 [get_ports {RSTB_R[1]}]
set_property PACKAGE_PIN F17 [get_ports {RSTB_R[2]}]
set_property PACKAGE_PIN F20 [get_ports {RSTB_R[3]}]
set_property PACKAGE_PIN A17 [get_ports {D_R[0]}]
set_property PACKAGE_PIN G15 [get_ports {D_R[1]}]
set_property PACKAGE_PIN E17 [get_ports {D_R[2]}]
set_property PACKAGE_PIN F19 [get_ports {D_R[3]}]
set_property PACKAGE_PIN A19 [get_ports {CK_R[0]}]
set_property PACKAGE_PIN H16 [get_ports {CK_R[1]}]
set_property PACKAGE_PIN F18 [get_ports {CK_R[2]}]
set_property PACKAGE_PIN G19 [get_ports {CK_R[3]}]
set_property PACKAGE_PIN C19 [get_ports {hold1[0]}]
set_property PACKAGE_PIN F15 [get_ports {hold1[1]}]
set_property PACKAGE_PIN K17 [get_ports {hold1[2]}]
set_property PACKAGE_PIN E20 [get_ports {hold1[3]}]
set_property PACKAGE_PIN B19 [get_ports {hold2[0]}]
set_property PACKAGE_PIN J15 [get_ports {hold2[1]}]
set_property PACKAGE_PIN M17 [get_ports {hold2[2]}]
set_property PACKAGE_PIN H19 [get_ports {hold2[3]}]

set_property IOSTANDARD LVCMOS33 [get_ports adc_clk_out]
set_property PACKAGE_PIN L23 [get_ports adc_clk_out]

set_property IOSTANDARD LVCMOS33 [get_ports {SC_CLK[*]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SC_DIN[*]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SC_DOUT[*]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SC_RSTb[*]}]
set_property PACKAGE_PIN B16 [get_ports {SC_CLK[0]}]
set_property PACKAGE_PIN D15 [get_ports {SC_CLK[1]}]
set_property PACKAGE_PIN E16 [get_ports {SC_CLK[2]}]
set_property PACKAGE_PIN D19 [get_ports {SC_CLK[3]}]
set_property PACKAGE_PIN A18 [get_ports {SC_DIN[0]}]
set_property PACKAGE_PIN D16 [get_ports {SC_DIN[1]}]
set_property PACKAGE_PIN G17 [get_ports {SC_DIN[2]}]
set_property PACKAGE_PIN D20 [get_ports {SC_DIN[3]}]
set_property PACKAGE_PIN C16 [get_ports {SC_DOUT[0]}]
set_property PACKAGE_PIN C18 [get_ports {SC_DOUT[1]}]
set_property PACKAGE_PIN E15 [get_ports {SC_DOUT[2]}]
set_property PACKAGE_PIN H18 [get_ports {SC_DOUT[3]}]
set_property PACKAGE_PIN K15 [get_ports {SC_RSTb[0]}]
set_property PACKAGE_PIN C17 [get_ports {SC_RSTb[1]}]
set_property PACKAGE_PIN J16 [get_ports {SC_RSTb[2]}]
set_property PACKAGE_PIN H17 [get_ports {SC_RSTb[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports iic_main_scl_io]
set_property IOSTANDARD LVCMOS33 [get_ports iic_main_sda_io]
set_property PACKAGE_PIN G22 [get_ports iic_main_scl_io]
set_property PACKAGE_PIN F23 [get_ports iic_main_sda_io]

set_property IOSTANDARD LVCMOS33 [get_ports stim_dac]
set_property PACKAGE_PIN C24 [get_ports stim_dac]
set_property IOSTANDARD LVCMOS33 [get_ports stim_drive]
set_property PACKAGE_PIN G20 [get_ports stim_drive]
set_property IOSTANDARD LVCMOS33 [get_ports {HV_RSTb[0]}]
set_property PACKAGE_PIN L19 [get_ports {HV_RSTb[0]}]
#BOARD LOCATION JUMPERS ON mobo; [1:0] are QUADPOS, [9:2] are APNUM
set_property PULLUP true [get_ports {board_loc[0]}]
set_property PULLUP true [get_ports {board_loc[1]}]
set_property PULLUP true [get_ports {board_loc[2]}]
set_property PULLUP true [get_ports {board_loc[3]}]
set_property PULLUP true [get_ports {board_loc[4]}]
set_property PULLUP true [get_ports {board_loc[5]}]
set_property PULLUP true [get_ports {board_loc[6]}]
set_property PULLUP true [get_ports {board_loc[7]}]
set_property PULLUP true [get_ports {board_loc[8]}]
set_property PULLUP true [get_ports {board_loc[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {board_loc[*]}]
#hw13: use one of the JP3 pins as board_loc[0] rather than the mobo connection
set_property PACKAGE_PIN H21 [get_ports {board_loc[0]}]
#set_property PACKAGE_PIN A20 [get_ports {board_loc[0]}]
set_property PACKAGE_PIN H24 [get_ports {board_loc[1]}]
set_property PACKAGE_PIN G26 [get_ports {board_loc[2]}]
set_property PACKAGE_PIN G21 [get_ports {board_loc[3]}]
set_property PACKAGE_PIN H23 [get_ports {board_loc[4]}]
set_property PACKAGE_PIN H22 [get_ports {board_loc[5]}]
set_property PACKAGE_PIN F25 [get_ports {board_loc[6]}]
set_property PACKAGE_PIN F22 [get_ports {board_loc[7]}]
set_property PACKAGE_PIN G25 [get_ports {board_loc[8]}]
set_property PACKAGE_PIN H26 [get_ports {board_loc[9]}]

#set_property IOSTANDARD LVCMOS33 [get_ports ext_trig_0]
#set_property PACKAGE_PIN D25 [get_ports ext_trig_0]

#set_property IOSTANDARD LVCMOS33 [get_ports {gpio_out[*]}]
#set_property PACKAGE_PIN C22 [get_ports {gpio_out[0]}]
#set_property PACKAGE_PIN D21 [get_ports {gpio_out[1]}]
#set_property PACKAGE_PIN D23 [get_ports {gpio_out[2]}]
#set_property PACKAGE_PIN D24 [get_ports {gpio_out[3]}]
#set_property PACKAGE_PIN E23 [get_ports {gpio_out[5]}]

#set_property IOSTANDARD LVDS [get_ports {SMA1_P[*]}]
#set_property PACKAGE_PIN AB17 [get_ports {SMA1_P[0]}]
#set_property IOSTANDARD LVCMOS33 [get_ports onepps]
#set_property IOSTANDARD LVCMOS33 [get_ports clk20]
#set_property PACKAGE_PIN E18 [get_ports clk20]
#set_property IOSTANDARD LVCMOS33 [get_ports fantach]
#set_property PACKAGE_PIN D18 [get_ports fantach]
#set_property IOSTANDARD LVCMOS33 [get_ports uid]
#set_property PACKAGE_PIN L20 [get_ports uid]
#set_property IOSTANDARD LVCMOS33 [get_ports sfp_sda]
#set_property PACKAGE_PIN F24 [get_ports sfp_sda]
#set_property IOSTANDARD LVCMOS33 [get_ports sfp_scl]
#set_property PACKAGE_PIN E26 [get_ports sfp_scl]
#set_property IOSTANDARD LVCMOS33 [get_ports {qdata[*]}]
#set_property PACKAGE_PIN J26 [get_ports {qdata[0]}]
#set_property PACKAGE_PIN J25 [get_ports {qdata[1]}]
#set_property PACKAGE_PIN J24 [get_ports {qdata[2]}]
#set_property PACKAGE_PIN K22 [get_ports {qdata[3]}]
#set_property PACKAGE_PIN K21 [get_ports {qdata[4]}]
#set_property PACKAGE_PIN L22 [get_ports {qdata[5]}]
#set_property PACKAGE_PIN J21 [get_ports {qdata[6]}]
#set_property PACKAGE_PIN M16 [get_ports {qdata[7]}]
#set_property IOSTANDARD LVDS [get_ports {OBUF_DS_P[*]}]
#set_property PACKAGE_PIN AD20 [get_ports {OBUF_DS_P[0]}]
#set_property PACKAGE_PIN V18 [get_ports {OBUF_DS_P[1]}]
#set_property PACKAGE_PIN W15 [get_ports {OBUF_DS_P[2]}]
#set_property PACKAGE_PIN AB14 [get_ports {OBUF_DS_P[3]}]
#set_property PACKAGE_PIN Y15 [get_ports {OBUF_DS_P[4]}]
#set_property PACKAGE_PIN AA17 [get_ports {OBUF_DS_P[5]}]
#set_property PACKAGE_PIN V14 [get_ports {OBUF_DS_P[6]}]
#set_property IOSTANDARD LVDS [get_ports {sysclk_p[*]}]
#set_property PACKAGE_PIN AB16 [get_ports {sysclk_p[0]}]

#pps_inout
set_property PACKAGE_PIN C26 [get_ports pps_inout_0]
set_property IOSTANDARD LVCMOS33 [get_ports pps_inout_0]

#flash spi(connect to flash chip)
#27 C23
#set_property PACKAGE_PIN C23 [get_ports falsh_spi_0_spi_ncs_o]
#set_property IOSTANDARD LVCMOS33 [get_ports falsh_spi_0_spi_ncs_o]
#28 B24
#set_property PACKAGE_PIN B24 [get_ports falsh_spi_0_spi_mosi_o]
#set_property IOSTANDARD LVCMOS33 [get_ports falsh_spi_0_spi_mosi_o]
#29 A25
#set_property PACKAGE_PIN A25 [get_ports falsh_spi_0_spi_miso_i]
#set_property IOSTANDARD LVCMOS33 [get_ports falsh_spi_0_spi_miso_i]
#27 C23 CS
set_property PACKAGE_PIN C23 [get_ports ss_o_0]
set_property IOSTANDARD LVCMOS33 [get_ports ss_o_0]
#28 B24
set_property PACKAGE_PIN B24 [get_ports mosi_o_0]
set_property IOSTANDARD LVCMOS33 [get_ports mosi_o_0]
#29 A25
set_property PACKAGE_PIN A25 [get_ports miso_i_0]
set_property IOSTANDARD LVCMOS33 [get_ports miso_i_0]

#set_property IOSTANDARD LVCMOS33 [get_ports J3pin1]
#set_property PACKAGE_PIN B20 [get_ports J3pin1]
#set_property PULLUP true [get_ports J3pin1]

#set_property DIFF_TERM TRUE [get_ports {sysclk_p[0]}]
#set_property DIFF_TERM TRUE [get_ports {sysclk_n[0]}]
set_property DIFF_TERM TRUE [get_ports {ADC_DIN_P[3]}]
set_property DIFF_TERM TRUE [get_ports {ADC_DIN_N[3]}]
set_property DIFF_TERM TRUE [get_ports {ADC_DIN_P[2]}]
set_property DIFF_TERM TRUE [get_ports {ADC_DIN_N[2]}]
set_property DIFF_TERM TRUE [get_ports {ADC_DIN_P[1]}]
set_property DIFF_TERM TRUE [get_ports {ADC_DIN_N[1]}]
set_property DIFF_TERM TRUE [get_ports {ADC_DIN_P[0]}]
set_property DIFF_TERM TRUE [get_ports {ADC_DIN_N[0]}]
set_property DIFF_TERM TRUE [get_ports {BIT_CLK_P[0]}]
set_property DIFF_TERM TRUE [get_ports {BIT_CLK_N[0]}]
set_property DIFF_TERM TRUE [get_ports FRM_CLK_P]
set_property DIFF_TERM TRUE [get_ports FRM_CLK_N]
#set_property DIFF_TERM TRUE [get_ports {SMA1_P[0]}]
#set_property DIFF_TERM TRUE [get_ports {SMA1_N[0]}]


set_property IOSTANDARD LVCMOS33 [get_ports {J3pin1[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports J3pin3]
set_property IOSTANDARD LVCMOS33 [get_ports J3pin4]
set_property IOSTANDARD LVCMOS33 [get_ports J3pin5]
set_property IOSTANDARD LVCMOS33 [get_ports J3pin6]
set_property PACKAGE_PIN B20 [get_ports {J3pin1[0]}]
#Use this as board_loc[0] til we all have Mobos
#set_property PACKAGE_PIN A20 [get_ports J3pin2]
set_property PACKAGE_PIN E21 [get_ports J3pin3]
set_property PULLDOWN true [get_ports J3pin3]
set_property PACKAGE_PIN E22 [get_ports J3pin4]
set_property PACKAGE_PIN C21 [get_ports J3pin5]
set_property PULLDOWN true [get_ports J3pin5]
set_property PACKAGE_PIN B21 [get_ports J3pin6]

set_property IOSTANDARD LVCMOS33 [get_ports SMA_J1]
set_property PACKAGE_PIN G24 [get_ports SMA_J1]

set_property CONFIG_MODE SPIx1 [current_design]

set_property IOSTANDARD LVCMOS33 [get_ports {focus_down_lim[0]}]
set_property PULLUP true [get_ports {focus_down_lim[0]}]
set_property PACKAGE_PIN K23 [get_ports {focus_down_lim[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports {focus_up_lim[0]}]
set_property PULLUP true [get_ports {focus_up_lim[0]}]
set_property PACKAGE_PIN E23 [get_ports {focus_up_lim[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports {shutter_down_lim[0]}]
set_property PACKAGE_PIN K22 [get_ports {shutter_down_lim[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports {shutter_up_lim[0]}]
set_property PACKAGE_PIN J24 [get_ports {shutter_up_lim[0]}]

#set_property IOSTANDARD LVCMOS33 [get_ports {step_drive[*]}]
#set_property PACKAGE_PIN C22 [get_ports {step_drive[0]}]
#set_property PACKAGE_PIN D23 [get_ports {step_drive[1]}]
#set_property PACKAGE_PIN D21 [get_ports {step_drive[2]}]
#set_property PACKAGE_PIN D24 [get_ports {step_drive[3]}]

set_property IOSTANDARD LVCMOS33 [get_ports {sd0_sc}]
set_property PACKAGE_PIN C22 [get_ports {sd0_sc}]
set_property IOSTANDARD LVCMOS33 [get_ports {sd1_ss}]
set_property PACKAGE_PIN D23 [get_ports {sd1_ss}]
set_property PULLDOWN true [get_ports sd1_ss]
set_property IOSTANDARD LVCMOS33 [get_ports {sd2_spare}]
set_property PACKAGE_PIN D21 [get_ports {sd2_spare}]
set_property IOSTANDARD LVCMOS33 [get_ports {sd3_lss}]
set_property PACKAGE_PIN D24 [get_ports {sd3_lss}]
set_property PULLDOWN true [get_ports sd3_lss]
#conflict
#set_property IOSTANDARD LVCMOS33 [get_ports {shutter_open[0]}]
#set_property PACKAGE_PIN J26 [get_ports {shutter_open[0]}]
#conflict
#set_property IOSTANDARD LVCMOS33 [get_ports {shutter_power[0]}]
#set_property PACKAGE_PIN J25 [get_ports {shutter_power[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports {focus_limits_on[0]}]
set_property PACKAGE_PIN K21 [get_ports {focus_limits_on[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports flash_dac]
set_property PACKAGE_PIN L18 [get_ports flash_dac]

set_property IOSTANDARD LVDS [get_ports flash_led_p]
set_property PACKAGE_PIN AA17 [get_ports flash_led_p]
set_property PACKAGE_PIN AA18 [get_ports flash_led_n]
set_property PACKAGE_PIN F6 [get_ports clk_125m_gtx_p_i_0]
set_property PACKAGE_PIN F5 [get_ports clk_125m_gtx_n_i_0]
#1 E18
set_property PACKAGE_PIN E18 [get_ports clk_20m_vcxo_i_0]
set_property IOSTANDARD LVCMOS33 [get_ports clk_20m_vcxo_i_0]
#19 L20
set_property PACKAGE_PIN L20 [get_ports onewire_b_0]
set_property IOSTANDARD LVCMOS33 [get_ports onewire_b_0]

#13 E26 def1--OK--SCL--QDATA6--J1-71
set_property PACKAGE_PIN J21 [get_ports user_sfp_0_sfp_mod_def1_b]
set_property IOSTANDARD LVCMOS33 [get_ports user_sfp_0_sfp_mod_def1_b]
set_property PULLUP true [get_ports user_sfp_0_sfp_mod_def1_b]
#14 F24 def2--OK--SDA--QDATA5--J1-69
set_property PACKAGE_PIN L22 [get_ports user_sfp_0_sfp_mod_def2_b]
set_property IOSTANDARD LVCMOS33 [get_ports user_sfp_0_sfp_mod_def2_b]
set_property PULLUP true [get_ports user_sfp_0_sfp_mod_def2_b]
#18 E25--OK
set_property PACKAGE_PIN E25 [get_ports user_sfp_0_sfp_los_i]
set_property IOSTANDARD LVCMOS33 [get_ports user_sfp_0_sfp_los_i]
set_property PULLUP true [get_ports user_sfp_0_sfp_los_i]

set_property PACKAGE_PIN G3 [get_ports user_sfp_0_sfp_rxn_i]
set_property PACKAGE_PIN G4 [get_ports user_sfp_0_sfp_rxp_i]
set_property PACKAGE_PIN F1 [get_ports user_sfp_0_sfp_txn_o]
set_property PACKAGE_PIN F2 [get_ports user_sfp_0_sfp_txp_o]



#set_property IOSTANDARD LVCMOS33 [get_ports pps_o_0]
#set_property PACKAGE_PIN B20 [get_ports pps_o_0]

set_property PACKAGE_PIN K16 [get_ports pll20dac_cs_n_o_0]
set_property IOSTANDARD LVCMOS33 [get_ports pll20dac_cs_n_o_0]

set_property PACKAGE_PIN D26 [get_ports pll25dac_cs_n_o_0]
set_property IOSTANDARD LVCMOS33 [get_ports pll25dac_cs_n_o_0]

set_property SLEW FAST [get_ports pps_inout_0]
set_property DRIVE 16 [get_ports pps_inout_0]



