#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2018.3_AR71948 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Sat Oct 12 15:43:50 PDT 2019
# SW Build 2405991 on Thu Dec  6 23:36:41 MST 2018
#
# Copyright 1986-2018 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
ExecStep()
{
"$@"
RETVAL=$?
if [ $RETVAL -ne 0 ]
then
exit $RETVAL
fi
}
ExecStep xelab -wto 85a87940f6d444f6a45619118a7e7fa8 --incr --debug typical --relax --mt 8 -L axis_infrastructure_v1_1_0 -L axis_register_slice_v1_1_18 -L axis_switch_v1_1_18 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip -L xpm --snapshot sim_switch_behav xil_defaultlib.sim_switch xil_defaultlib.glbl -log elaborate.log
