webtalk_init -webtalk_dir /media/wei/DATA/LW/Project/Vivado_Project/IP_Cores_PanoSETI/Eth_Core_Ctrl/Eth_Core_Ctrl.sim/sim_1/behav/xsim/xsim.dir/sim_ETH_CORE_CTRL_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Wed Oct  9 22:36:27 2019" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.3_AR71948 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2405991" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "211461594_0_0_563" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "42db0f94-26b3-4483-9fa5-74de1c726b69" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "d4d814642a5c467ba8d284aa222426d4" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "22" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 18.04.3 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "960.863 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "25.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "41 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.04_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "130260_KB" -context "xsim\\usage"
webtalk_transmit -clientid 404102804 -regid "211461594_0_0_563" -xml /media/wei/DATA/LW/Project/Vivado_Project/IP_Cores_PanoSETI/Eth_Core_Ctrl/Eth_Core_Ctrl.sim/sim_1/behav/xsim/xsim.dir/sim_ETH_CORE_CTRL_behav/webtalk/usage_statistics_ext_xsim.xml -html /media/wei/DATA/LW/Project/Vivado_Project/IP_Cores_PanoSETI/Eth_Core_Ctrl/Eth_Core_Ctrl.sim/sim_1/behav/xsim/xsim.dir/sim_ETH_CORE_CTRL_behav/webtalk/usage_statistics_ext_xsim.html -wdm /media/wei/DATA/LW/Project/Vivado_Project/IP_Cores_PanoSETI/Eth_Core_Ctrl/Eth_Core_Ctrl.sim/sim_1/behav/xsim/xsim.dir/sim_ETH_CORE_CTRL_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
