# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config -id {HDL-1065} -limit 10000
create_project -in_memory -part xc7k160tfbg676-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /media/wei/DATA/LW/Project/Vivado_Project/IP_Cores_PanoSETI/AXI_Stream_Switch/AXI_Stream_Switch.cache/wt [current_project]
set_property parent.project_path /media/wei/DATA/LW/Project/Vivado_Project/IP_Cores_PanoSETI/AXI_Stream_Switch/AXI_Stream_Switch.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths /media/wei/DATA/LW/Project/Vivado_Project/IP_Cores_PanoSETI/AXI_Stream_Switch/AXI_Stream_Switch.srcs/sources_1 [current_project]
update_ip_catalog
set_property ip_output_repo /media/wei/DATA/LW/Project/Vivado_Project/IP_Cores_PanoSETI/AXI_Stream_Switch/AXI_Stream_Switch.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib /media/wei/DATA/LW/Project/Vivado_Project/IP_Cores_PanoSETI/AXI_Stream_Switch/AXI_Stream_Switch.srcs/sources_1/new/AXI_Stream_Switch.v
read_ip -quiet /media/wei/DATA/LW/Project/Vivado_Project/IP_Cores_PanoSETI/AXI_Stream_Switch/AXI_Stream_Switch.srcs/sources_1/ip/axis_switch_0/axis_switch_0.xci
set_property used_in_implementation false [get_files -all /media/wei/DATA/LW/Project/Vivado_Project/IP_Cores_PanoSETI/AXI_Stream_Switch/AXI_Stream_Switch.srcs/sources_1/ip/axis_switch_0/axis_switch_0_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top AXI_Stream_Switch -part xc7k160tfbg676-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef AXI_Stream_Switch.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file AXI_Stream_Switch_utilization_synth.rpt -pb AXI_Stream_Switch_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
