# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: ip/axis_switch_0/axis_switch_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axis_switch_0 || ORIG_REF_NAME==axis_switch_0} -quiet] -quiet

# XDC: ip/axis_switch_0/axis_switch_0_ooc.xdc
