# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/XilinxProjects/PANOSETI/QuadrantBoard/ip_repo/maroc_slow_control_1.0/src/fifo_32by128/fifo_32by128.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fifo_32by128 || ORIG_REF_NAME==fifo_32by128} -quiet] -quiet

# XDC: c:/XilinxProjects/PANOSETI/QuadrantBoard/ip_repo/maroc_slow_control_1.0/src/fifo_32by128/fifo_32by128.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_32by128 || ORIG_REF_NAME==fifo_32by128} -quiet] {/U0 } ]/U0 ] -quiet] -quiet
