#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2018.3_AR71948 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Wed Oct 09 22:36:06 PDT 2019
# SW Build 2405991 on Thu Dec  6 23:36:41 MST 2018
#
# Copyright 1986-2018 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
ExecStep()
{
"$@"
RETVAL=$?
if [ $RETVAL -ne 0 ]
then
exit $RETVAL
fi
}
ExecStep xsim sim_ETH_CORE_CTRL_behav -key {Behavioral:sim_1:Functional:sim_ETH_CORE_CTRL} -tclbatch sim_ETH_CORE_CTRL.tcl -log simulate.log
